// AUTO-GENERATED โดย scripts/ingest-product-images.mjs — อย่าแก้มือ
// แมพ SKU → รูปสินค้า (public/products) + หมวด
export interface ProductImage { img: string; category: string }
export const PRODUCT_IMAGES: Record<string, ProductImage> = {
  'C1-15G': { img: '/products/C1-15G.png', category: "Treatment & Mask" },
  'C1-6G': { img: '/products/C1-6G.png', category: "Treatment & Mask" },
  'C1-6Gx6': { img: '/products/C1-6Gx6.png', category: "Treatment & Mask" },
  'C2-35G': { img: '/products/C2-35G.png', category: "Serum" },
  'C2-8G': { img: '/products/C2-8G.png', category: "Serum" },
  'C2-8Gx6': { img: '/products/C2-8Gx6.png', category: "Serum" },
  'C3-30G': { img: '/products/C3-30G.png', category: "Sunscreen" },
  'C3-7G': { img: '/products/C3-7G.png', category: "Sunscreen" },
  'C3-7GX6': { img: '/products/C3-7GX6.png', category: "Sunscreen" },
  'C4-35G': { img: '/products/C4-35G.png', category: "Serum" },
  'C4-8G': { img: '/products/C4-8G.png', category: "Serum" },
  'C4-8GX6': { img: '/products/C4-8GX6.png', category: "Serum" },
  'D2-70G': { img: '/products/D2-70G.png', category: "Oral care (JDENT)" },
  'D3-70G': { img: '/products/D3-70G.png', category: "Oral care (JDENT)" },
  'JH904-70G': { img: '/products/JH904-70G.png', category: "Cleanser" },
  'JH904-70Gx4': { img: '/products/JH904-70Gx4.png', category: "Cleanser" },
  'JH905-70G': { img: '/products/JH905-70G.png', category: "Cleanser" },
  'JH905-70Gx4': { img: '/products/JH905-70Gx4.png', category: "Cleanser" },
  'JH906-70G': { img: '/products/JH906-70G.png', category: "Cleanser" },
  'JH906-70Gx4': { img: '/products/JH906-70Gx4.png', category: "Cleanser" },
  'JHA1-40G': { img: '/products/JHA1-40G.png', category: "Body lotion" },
  'JHA1-40GX6': { img: '/products/JHA1-40GX6.png', category: "Body lotion" },
  'JHA2-40G': { img: '/products/JHA2-40G.png', category: "Cleanser" },
  'JHA2-40GX6': { img: '/products/JHA2-40GX6.png', category: "Cleanser" },
  'JHD1-70G': { img: '/products/JHD1-70G.png', category: "Oral care (JDENT)" },
  'JHK2-40G': { img: '/products/JHK2-40G.png', category: "Serum" },
  'JHK3-30G': { img: '/products/JHK3-30G.png', category: "Serum" },
  'JHK4-48G': { img: '/products/JHK4-48G.png', category: "Moister" },
  'JHL5-15Gx6': { img: '/products/JHL5-15Gx6.png', category: "Moister" },
  'JHM2-4G': { img: '/products/JHM2-4G.png', category: "Treatment & Mask" },
  'JHM2-4Gx6': { img: '/products/JHM2-4Gx6.png', category: "Treatment & Mask" },
  'JHT1-2G': { img: '/products/JHT1-2G.png', category: "Make up" },
  'JHT1-2Gx6': { img: '/products/JHT1-2Gx6.png', category: "Make up" },
  'JHT2-2G': { img: '/products/JHT2-2G.png', category: "Make up" },
  'JHT2-2Gx6': { img: '/products/JHT2-2Gx6.png', category: "Make up" },
  'JHT3-2G': { img: '/products/JHT3-2G.png', category: "Make up" },
  'JHT3-2Gx6': { img: '/products/JHT3-2Gx6.png', category: "Make up" },
  'L1-150G': { img: '/products/L1-150G.png', category: "Body lotion" },
  'L10-30G': { img: '/products/L10-30G.png', category: "Sunscreen" },
  'L10-7G': { img: '/products/L10-7G.png', category: "Sunscreen" },
  'L10-7Gx6': { img: '/products/L10-7Gx6.png', category: "Sunscreen" },
  'L11-400G': { img: '/products/L11-400G.png', category: "Body lotion" },
  'L11-40G': { img: '/products/L11-40G.png', category: "Body lotion" },
  'L11-40Gx6': { img: '/products/L11-40Gx6.png', category: "Body lotion" },
  'L12-400G': { img: '/products/L12-400G.png', category: "Cleanser" },
  'L13-10G': { img: '/products/L13-10G.png', category: "Body lotion" },
  'L13-10Gx6': { img: '/products/L13-10Gx6.png', category: "Body lotion" },
  'L13-40G': { img: '/products/L13-40G.png', category: "Body lotion" },
  'L14-40G': { img: '/products/L14-40G.png', category: "Cleanser" },
  'L14-40Gx6': { img: '/products/L14-40Gx6.png', category: "Cleanser" },
  'L14-70G': { img: '/products/L14-70G.png', category: "Cleanser" },
  'L19-48G': { img: '/products/L19-48G.png', category: "Moister" },
  'L19-8G': { img: '/products/L19-8G.png', category: "Moister" },
  'L19-8Gx6': { img: '/products/L19-8Gx6.png', category: "Moister" },
  'L20-30G': { img: '/products/L20-30G.png', category: "Sunscreen" },
  'L20-7G': { img: '/products/L20-7G.png', category: "Sunscreen" },
  'L20-7Gx6': { img: '/products/L20-7Gx6.png', category: "Sunscreen" },
  'L21-100G': { img: '/products/L21-100G.png', category: "Sunscreen" },
  'L3-40G': { img: '/products/L3-40G.png', category: "Sunscreen" },
  'L3-8G': { img: '/products/L3-8G.png', category: "Sunscreen" },
  'L3-8Gx6': { img: '/products/L3-8Gx6.png', category: "Sunscreen" },
  'L4-40G': { img: '/products/L4-40G.png', category: "Serum" },
  'L4-8G': { img: '/products/L4-8G.png', category: "Serum" },
  'L4-8Gx6': { img: '/products/L4-8Gx6.png', category: "Serum" },
  'L5-15G': { img: '/products/L5-15G.png', category: "Moister" },
  'L5-90G': { img: '/products/L5-90G.png', category: "Moister" },
  'L5A-90G': { img: '/products/L5A-90G.png', category: "Moister" },
  'L6-40G': { img: '/products/L6-40G.png', category: "Serum" },
  'L6-8G': { img: '/products/L6-8G.png', category: "Serum" },
  'L6-8Gx6': { img: '/products/L6-8Gx6.png', category: "Serum" },
  'L7-30G': { img: '/products/L7-30G.png', category: "Serum" },
  'L7-6G': { img: '/products/L7-6G.png', category: "Serum" },
  'L7-6Gx6': { img: '/products/L7-6Gx6.png', category: "Serum" },
  'L8A-30G': { img: '/products/L8A-30G.png', category: "Make up" },
  'L8A-6G': { img: '/products/L8A-6G.png', category: "Make up" },
  'L8A-6Gx6': { img: '/products/L8A-6Gx6.png', category: "Make up" },
  'L8B-30G': { img: '/products/L8B-30G.png', category: "Make up" },
  'L8B-6G': { img: '/products/L8B-6G.png', category: "Make up" },
  'L8B-6Gx6': { img: '/products/L8B-6Gx6.png', category: "Make up" },
  'L9-8G': { img: '/products/L9-8G.png', category: "Moister" },
  'L9-8Gx6': { img: '/products/L9-8Gx6.png', category: "Moister" },
  'R1-30G': { img: '/products/R1-30G.png', category: "Serum" },
  'R2-30G': { img: '/products/R2-30G.png', category: "Moister" },
  'S4-70G': { img: '/products/S4-70G.png', category: "Cleanser" },
  'S4-70Gx6': { img: '/products/S4-70Gx6.png', category: "Cleanser" },
  'T5A-2.5G': { img: '/products/T5A-2.5G.png', category: "Make up" },
  'T5A-2G': { img: '/products/T5A-2G.png', category: "Make up" },
  'T5A-2Gx6': { img: '/products/T5A-2Gx6.png', category: "Make up" },
  'T5B-2.5G': { img: '/products/T5B-2.5G.png', category: "Make up" },
  'T5B-2G': { img: '/products/T5B-2G.png', category: "Make up" },
  'T5B-2Gx6': { img: '/products/T5B-2Gx6.png', category: "Make up" },
  'T5C-2G': { img: '/products/T5C-2G.png', category: "Make up" },
  'T5C-2Gx6': { img: '/products/T5C-2Gx6.png', category: "Make up" },
  'T6A-10G': { img: '/products/T6A-10G.png', category: "Make up" },
  'T6A-5G': { img: '/products/T6A-5G.png', category: "Make up" },
  'V1-14C': { img: '/products/V1-14C.png', category: "Supplement (Jarvit)" },
}

// หมวดทั้งหมด (จากโฟลเดอร์)
export const PRODUCT_CATEGORIES = ["Body lotion","Cleanser","Make up","Moister","Oral care (JDENT)","Serum","Sunscreen","Supplement (Jarvit)","Treatment & Mask"] as const

export const productImage = (sku: string): string | null => PRODUCT_IMAGES[sku]?.img ?? null
export const productCategory = (sku: string): string | null => PRODUCT_IMAGES[sku]?.category ?? null
